include:
  - "https://gitlab.esss.lu.se/ics-infrastructure/gitlab-ci-yml/raw/master/ArtifactoryPyPI.gitlab-ci.yml"

# stages:
#   - test
#   - analyse

unittest:
  stage: test
  image: "python:3.10"
  script:
    - python --version
    - pip install . --index-url https://artifactory.esss.lu.se/artifactory/api/pypi/pypi-virtual/simple
    - pip install coverage pytest
    - pytest --junitxml=report.xml
    - coverage run -m unittest -v
    - coverage xml
    - coverage report
  coverage: '/^TOTAL\s+\d+\s+\d+\s+(\d+)/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

variables:
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

style_check:
  stage: check
  image: registry.esss.lu.se/ics-docker/pre-commit
  script:
    - pre-commit run --all-files

sonar-scanner:
  stage: analyse
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=pychiver -Dsonar.projectVersion=$CI_COMMIT_REF_NAME -Dsonar.sources=pychiver,tests -Dsonar.host.url=https://sonarqube.esss.lu.se
  only:
    - branches@accop/pytools/pychiver
